### ISSUE TITLE
[Minor] What do you even do for 'blue' when text is black. I do not understand

### ISSUE THREAD

**Issue by DianaCondon** [hyperStroop/hyperStroop#32]
Confusing instructions, user frustrated

**Comment by DianaCondon** [comment]
Recreation Steps: 
After Pressing start, I always get a 'Blue' prompt, which was not gone over in the tutorial.

**Comment by DianaCondon** [comment]
I think Blue plus black may equal purple (more than others would) so I pressed space, but that just jumped me down the page

**Comment by DianaCondon** [comment]
Testing on Safari

**Comment by BossJ** [comment]
Issues 30-35 reported the same issues reported in issues 28 and 29.
