### ISSUE TITLE
[Major] Game does not start

### ISSUE THREAD

**Issue by FXStrato** [hyperStroop/hyperStroop#33]
After clicking on start, and having the countdown occur and navigating to this page, the F, J, and Space keys don't do anything, restarting doesn't change anything. Clicking on back to tutorial does bring me back to the home page, and leaderboard does take me to leader board.

One thing I noticed in console is that jQuery is not being loaded. Is this perhaps the reason?

**Comment by BossJ** [comment]
Issues 30-35 reported the same issues reported in issues 28 and 29.
